<?php declare(strict_types=1);

/** @version 1.1.0 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$cssProperties = (array)$block->getCssProperties();
?>
<style>
    :root {
    <?php foreach ($cssProperties as $cssPropertyName => $cssPropertyValue): ?>
        --<?= $escaper->escapeHtml($cssPropertyName); ?>: <?= $escaper->escapeHtml($cssPropertyValue); ?>;
    <?php endforeach; ?>
    }
</style>
